language: node_js
node_js:
  - '0.10'
before_install:
  - currentfolder=${PWD##*/}
  - if [ "$currentfolder" != 'generator-ezexpress' ]; then cd .. && eval "mv $currentfolder generator-ezexpress" && cd generator-ezexpress; fi

